In [1]:
import numpy as np


# 실습 과제1: NumPy를 활용한 행렬 변형 실습

## 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.


In [14]:
A = np.random.rand(6,5)
A

array([[0.82938411, 0.07422311, 0.81313836, 0.34110034, 0.16689479],
       [0.69040108, 0.16496371, 0.07213877, 0.93737029, 0.24336809],
       [0.74781602, 0.92997049, 0.57722681, 0.75434484, 0.21302744],
       [0.90059962, 0.84016624, 0.42156753, 0.30447651, 0.38406622],
       [0.29630077, 0.81466079, 0.94524311, 0.850456  , 0.81328852],
       [0.5387934 , 0.65363535, 0.02618508, 0.91764746, 0.33072852]])

## 문제 2: 새로운 축 추가

행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [15]:
B = A[:,np.newaxis]
B.shape

(6, 1, 5)

In [12]:
B = A[:,None,:]
# 동일한 결과

문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [16]:
B[2,:, :] = 0.3
B

array([[[0.82938411, 0.07422311, 0.81313836, 0.34110034, 0.16689479]],

       [[0.69040108, 0.16496371, 0.07213877, 0.93737029, 0.24336809]],

       [[0.3       , 0.3       , 0.3       , 0.3       , 0.3       ]],

       [[0.90059962, 0.84016624, 0.42156753, 0.30447651, 0.38406622]],

       [[0.29630077, 0.81466079, 0.94524311, 0.850456  , 0.81328852]],

       [[0.5387934 , 0.65363535, 0.02618508, 0.91764746, 0.33072852]]])


문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [17]:
C = A[None,:,:]
D = A[:,:,None]
C.shape, D.shape

((1, 6, 5), (6, 5, 1))


문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [ ]:
D[-3,:,:]=0.8

In [25]:
A = np.random.rand(6,5)
D = A[:,:,None]
A.shape, D.shape

((6, 5), (6, 5, 1))

In [26]:
D[-3:,:,:]=0.8

In [ ]:
A,D # 왜 A도 수정된건지? D는 A의 뷰이므로 뷰를 수정하면 원본도 같이 수정됨

(array([[0.51454461, 0.36827856, 0.35168702, 0.51300553, 0.68849447],
        [0.70390321, 0.0516209 , 0.94134229, 0.30468609, 0.43126094],
        [0.78646421, 0.17015832, 0.35415196, 0.77985885, 0.81125328],
        [0.8       , 0.8       , 0.8       , 0.8       , 0.8       ],
        [0.8       , 0.8       , 0.8       , 0.8       , 0.8       ],
        [0.8       , 0.8       , 0.8       , 0.8       , 0.8       ]]),
 array([[[0.51454461],
         [0.36827856],
         [0.35168702],
         [0.51300553],
         [0.68849447]],
 
        [[0.70390321],
         [0.0516209 ],
         [0.94134229],
         [0.30468609],
         [0.43126094]],
 
        [[0.78646421],
         [0.17015832],
         [0.35415196],
         [0.77985885],
         [0.81125328]],
 
        [[0.8       ],
         [0.8       ],
         [0.8       ],
         [0.8       ],
         [0.8       ]],
 
        [[0.8       ],
         [0.8       ],
         [0.8       ],
         [0.8       ],
         [0.8 