In [3]:
#p.97
import numpy as np

data = np.random.normal(0,1,10)
data

array([-0.14611976, -0.19826563, -0.44353975,  0.04376426, -0.77338117,
       -0.55224823, -0.0277685 ,  1.05132799,  0.19795266, -0.70288709])

In [ ]:
#argmin, argmax: 배열에서 가장 작은/큰 값이 어디에 있는지(위치/인덱스)
np.argmin(data), np.argmax(data)

(np.int64(4), np.int64(7))

In [5]:
i1 = np.argmin(data)
i2 = np.argmax(data)
i1,i2, data[i1],data[i2]

(np.int64(4),
 np.int64(7),
 np.float64(-0.7733811660800654),
 np.float64(1.0513279931763786))

In [6]:
np.sort(data)

array([-0.77338117, -0.70288709, -0.55224823, -0.44353975, -0.19826563,
       -0.14611976, -0.0277685 ,  0.04376426,  0.19795266,  1.05132799])

In [ ]:
# argsort: 배열의 모든 원소를 정렬했을 때의 순서를 인덱스로 알려줌
np.argsort(data)

array([4, 9, 5, 2, 1, 0, 6, 3, 8, 7])

In [10]:
idx = np.argsort(data)
data[idx][:3]

array([-0.77338117, -0.70288709, -0.55224823])

In [12]:
data = np.random.randint(0,10,(4,6))
data.shape, data

((4, 6),
 array([[5, 4, 6, 9, 0, 3],
        [6, 4, 1, 8, 5, 8],
        [2, 1, 4, 5, 5, 1],
        [4, 6, 4, 2, 8, 4]], dtype=int32))

In [ ]:
np.sort(data, axis=1) # 행 별로 정렬됨(디폴트, axis 설정하지 않으면 자동으로 행정렬)

array([[0, 3, 4, 5, 6, 9],
       [1, 4, 5, 6, 8, 8],
       [1, 1, 2, 4, 5, 5],
       [2, 4, 4, 4, 6, 8]], dtype=int32)

In [ ]:
np.sort(data, axis=0) # 열별로 정렬됨

array([[2, 1, 1, 2, 0, 1],
       [4, 4, 4, 5, 5, 3],
       [5, 4, 4, 8, 5, 4],
       [6, 6, 6, 9, 8, 8]], dtype=int32)

In [15]:
#p.100
data = np.random.randint(0,10,7)
data

array([1, 3, 9, 8, 5, 4, 7], dtype=int32)

In [26]:
data = np.arange(1,100)
np.random.shuffle(data)
data

array([64, 15,  1, 20, 57, 59, 74, 16, 43,  9, 90, 52, 91, 41, 13, 47, 12,
       66, 62, 14, 89, 42, 67, 97, 82,  5, 61, 44, 98, 65, 72, 69, 60, 81,
       45, 19, 50,  4, 92, 70, 39, 77, 51, 36, 95, 10, 85, 54, 87, 96, 24,
       73, 22, 48, 35, 55, 83, 23, 17, 80, 94, 30, 68, 53, 38, 32, 78,  3,
       99, 18, 79, 26, 84, 93, 33, 25,  8, 49, 31, 46, 37,  2, 56, 75, 71,
       29, 27, 40, 88, 11,  6,  7, 28, 34, 21, 86, 76, 63, 58])

In [ ]:
# np.partition(a, k): 배열 a에서 k번째로 작은 값을 찾아 제자리에 놓고, 그 값보다 작은 것들은 왼쪽, 큰 것들은 오른쪽으로 분할(partition)만 함
np.partition(data,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 76,
       59, 57, 78, 43, 74, 47, 41, 52, 38, 53, 68, 62, 66, 80, 82, 67, 42,
       72, 65, 44, 61, 45, 81, 60, 69, 79, 83, 55, 35, 48, 49, 33, 73, 54,
       37, 46, 71, 75, 56, 36, 51, 77, 40, 39, 70, 50, 63, 58, 64, 86, 88,
       93, 84, 99, 98, 97, 89, 91, 90, 94, 96, 87, 85, 95, 92])